### ISSUE TITLE
Remove protected visibility modifier

### ISSUE THREAD

**Issue by Dallanosm** [worldline-spain/t21_kotlin_base_project#2]
https://github.com/worldline-spain/t21_kotlin_base_project/blob/555883d50bc69d81858324722d49e7e79793e207/domain/src/main/java/com/worldline/domain/interactor/ObservableInteractor.kt#L14

**Comment by sergiocasero** [comment]
This issue will be solved with PR https://github.com/worldline-spain/t21_kotlin_base_project/pull/3
